module.exports = {
  mongodbError: 'MongoDB Error',
  singupDone: 'Congrats! You are successfully signed up',
  signupFailed: 'Opps...! signup failed',
  emailExist: 'Email already exist',
  nameNotFound: 'Name not found',
  emailNotFound: 'Email not found',
  passwordNotFound: 'Password not found',
  userLoggedIn: 'User logged in successfully',
  invalidPassword: 'Invalid user paassword',
  invalidUserEmail: 'Invalid user email',
  postCreated: 'Post created successfully',
  postCreationFailed: 'Post creation failed',
  tokenHasExpired: 'Token has expired',
  tokenNotFound: 'Token not found',
  invalidToken: 'Invalid token',
  postFetched: 'All posts fetched successfully',
  postsNotFound: 'Posts not found',
  postFound: 'Post fetched successfully',
  postNotFound: 'Post not found',
  commentAdded: 'Comment added successfully',
  invalidPostId: 'Invalid post id',
  commentNotAdded: 'Comments not not added',
  commentIsEmpty: 'Comment should not be empty',
  responseAdded: 'Response added',
  responseNotAdded: 'Respnse not added',
  postTitleMissing: 'Post title missing',
  postContentMissing: 'Post content missing',
  userIdMissing: 'User id missing',
};
